app = "wagtail-starter-demo"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DATABASE_URL = "sqlite:///data/db.sqlite3"
  MEDIA_ROOT = "/data/media"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20

[mounts]
  source = "wagtail"
  destination = "/data"
  initial_size = "1GB"
  auto_extend_size_limit = "3GB"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  cpus = 1
  cpu_kind = "shared"
